site_name: iothings.io Documentation
site_url: https://iothings-io.github.io/
theme:
  name: material  # Ini tema paling populer dan profesional untuk dokumentasi
  palette:
    primary: indigo
    accent: indigo

nav:
  - Beranda: index.md
  - Produk & Panduan:
      - Zigbee Gateway: gateway.md
      - RS485 Bridge: rs485.md
  - Marketplace: catalog.md
